// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoGbaTufIqsk7NrfWPihOwPppSH2YivbY',
    appId: '1:545349632082:web:4dbb1c693e538bdc55df8b',
    messagingSenderId: '545349632082',
    projectId: 'smartshelf-d9881',
    authDomain: 'smartshelf-d9881.firebaseapp.com',
    databaseURL: 'https://smartshelf-d9881-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smartshelf-d9881.appspot.com',
    measurementId: 'G-J346X01L00',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8zCrmbS2VnKbc-IZuWLKrVC779P0kjOs',
    appId: '1:545349632082:android:7308074a2bb5ab6d55df8b',
    messagingSenderId: '545349632082',
    projectId: 'smartshelf-d9881',
    databaseURL: 'https://smartshelf-d9881-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smartshelf-d9881.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNw5cTocJXDRmratjFqM5aQUcq8ejPyA0',
    appId: '1:545349632082:ios:99159ae6b9c71a5255df8b',
    messagingSenderId: '545349632082',
    projectId: 'smartshelf-d9881',
    databaseURL: 'https://smartshelf-d9881-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smartshelf-d9881.appspot.com',
    iosClientId: '545349632082-gsukaivhbdjp0ark295ujpn6oqat8r1t.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartshelfApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNw5cTocJXDRmratjFqM5aQUcq8ejPyA0',
    appId: '1:545349632082:ios:99159ae6b9c71a5255df8b',
    messagingSenderId: '545349632082',
    projectId: 'smartshelf-d9881',
    databaseURL: 'https://smartshelf-d9881-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smartshelf-d9881.appspot.com',
    iosClientId: '545349632082-gsukaivhbdjp0ark295ujpn6oqat8r1t.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartshelfApp',
  );
}
